version: "3.8"
services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: long-distance-ice-skating
    ports:
      - "5432:5432"
    volumes:
      - "./init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql"
  flask:
    build: .
    ports:
      - "8080:5000"
    environment:
      PG_PASSWORD: long-distance-ice-skating
    depends_on:
      - postgres
